### PR TITLE
add first article to ecma, and add icon an text in readme

### PR DESCRIPTION
**Pull request by darlanmendonca**
I implement a first article, thinking in new developers, to say what fuck is EcmaScript, and Heyy, look to this, is what you will learn in our articles too, continuosly, rs

### CODE REVIEW

**Comment by darlanmendonca** [comment]
@WendellAdriel @khaosdoctor when you can, give a look please, I want write more articles like this, but before, I want your suggestions if there is

**Review by khaosdoctor — CHANGES_REQUESTED** [review]
I proposed a change in another commit, see if you liked it

**Comment by darlanmendonca** [comment]
all right!! I really dont can choose between frontend and front end. I dont like front-end, rs

But, I dont have sure, here http://english.stackexchange.com/questions/34447/is-it-front-end-frontend-or-front-end, if I really understand, the correct is front end

What you think?

**Comment by khaosdoctor** [comment]
Well, linguistics was never my strong point haha I write front-end just because it looks better to the eyes

**Comment by darlanmendonca** [comment]
:D

**Pull request merged**
